language: node_js
branches:
  except:
  - feature
  only:
  - master
  - stable
node_js:
  - 10
cache:
  directories:
    - node_modules
before_script:
  - cd vue.js-vuetify-cd
script:
  - npm run test:unit